# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-25 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureStudent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('present', models.CharField(max_length=1)),
                ('attention_percent', models.FloatField(blank=True, null=True)),
                ('emotion_data', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'lecture_student',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LectureTeacher',
            fields=[
                ('lecture_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lecture_start_time', models.DateTimeField()),
                ('lecture_end_time', models.DateTimeField()),
                ('subject', models.CharField(blank=True, max_length=50, null=True)),
                ('topic', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'db_table': 'lecture_teacher',
                'managed': False,
            },
        ),
    ]
